/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Ergoni (https://sketchfab.com/Ergoni)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/magical-find-944ad1c760b14f3ca4f5a6039744bfdf
Title: Magical Find
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function Model(props) {
  const { nodes, materials } = useGLTF("/magical_find.glb");
  return (
    <group {...props} dispose={null}>
      <group scale={0.02}>
        <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Stump_Props_0.geometry}
            material={materials.Props}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Stump_OutLine_0.geometry}
            material={materials.OutLine}
          />
        </group>
        <group
          position={[14.109, 171.582, 0]}
          rotation={[0, 0, -0.247]}
          scale={100}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Sword_Props_0.geometry}
            material={materials.Props}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Sword_OutLine_0.geometry}
            material={materials.OutLine}
          />
        </group>
        <group
          position={[-303.32, 22.966, -74.826]}
          rotation={[-Math.PI / 2, 0, 1.094]}
          scale={100}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Frog_2_OutLine_0.geometry}
            material={materials.OutLine}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Frog_2_Frogs_0.geometry}
            material={materials.Frogs}
          />
        </group>
        <group
          position={[-125.288, 125.533, -86.158]}
          rotation={[-1.999, -0.402, 0.646]}
          scale={100}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Frog_1_OutLine_0.geometry}
            material={materials.OutLine}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Frog_1_Frogs_0.geometry}
            material={materials.Frogs}
          />
        </group>
        <group
          position={[263.656, 22.966, -74.826]}
          rotation={[-Math.PI / 2, 0, -0.917]}
          scale={100}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Frog_3_OutLine_0.geometry}
            material={materials.OutLine}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Frog_3_Frogs_0.geometry}
            material={materials.Frogs}
          />
        </group>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Light_Light_0.geometry}
          material={materials.Light}
          position={[-0.286, 157.865, 0.04]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Leaf_4001_Ext_0.geometry}
          material={materials.material}
          position={[78.125, 31.528, 98.881]}
          rotation={[0, 0.304, 0]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Leaf_2004_Ext_0.geometry}
          material={materials.material}
          position={[-101.275, 21.58, 85.642]}
          rotation={[-0.688, 0.084, -3.117]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Leaf_4002_Ext_0.geometry}
          material={materials.material}
          position={[68.487, 29.127, -100.799]}
          rotation={[-3.138, 0.115, 3.108]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Leaf_4_Ext_0.geometry}
          material={materials.material}
          position={[52.726, 19.096, -107.447]}
          rotation={[-3.137, 0.586, 3.106]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Leaf_2003_Ext_0.geometry}
          material={materials.material}
          position={[-122.598, -1.967, -67.831]}
          rotation={[-1.513, -0.365, -1.606]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Leaf_5002_Ext_0.geometry}
          material={materials.material}
          position={[-300.899, 52.812, -290.894]}
          rotation={[0, 0.717, 0]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Leaf_5003_Ext_0.geometry}
          material={materials.material}
          position={[-29.174, 35.89, -418.951]}
          rotation={[0, 0.171, 0]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Leaf_5001_Ext_0.geometry}
          material={materials.material}
          position={[-92.421, 24.254, 414.54]}
          rotation={[0, -0.072, 0]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Leaf_2001_Ext_0.geometry}
          material={materials.material}
          position={[-388.66, 32.515, -194.574]}
          rotation={[-1.232, 0.384, -2.355]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Leaf_2002_Ext_0.geometry}
          material={materials.material}
          position={[164.96, 16.779, -358.238]}
          rotation={[-0.722, 0.14, -0.04]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Leaf_5_Ext_0.geometry}
          material={materials.material}
          position={[-390.069, 54.038, 155.33]}
          rotation={[Math.PI, 1.281, -Math.PI]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Leaf_5004_Ext_0.geometry}
          material={materials.material}
          position={[415.883, 52.812, 46.917]}
          rotation={[Math.PI, -1.373, Math.PI]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Leaf_5005_Ext_0.geometry}
          material={materials.material}
          position={[385.567, 28.057, -162.783]}
          rotation={[0, -1.257, 0]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Leaf_2005_Ext_0.geometry}
          material={materials.material}
          position={[393.695, 2.311, 110.568]}
          rotation={[-1.05, 0.017, -0.853]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Leaf_1001_Ext_0.geometry}
          material={materials.material}
          position={[28.197, 45.797, 117.879]}
          rotation={[0, 0.25, 0]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Leaf_1002_Ext_0.geometry}
          material={materials.material}
          position={[2.001, 22.212, 127.605]}
          rotation={[Math.PI, -0.25, Math.PI]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Leaf_1003_Ext_0.geometry}
          material={materials.material}
          position={[118.276, 56.683, -29.61]}
          rotation={[Math.PI, 1.348, -Math.PI]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Leaf_1004_Ext_0.geometry}
          material={materials.material}
          position={[127.278, 33.098, -3.157]}
          rotation={[0, -1.348, 0]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Leaf_1010_Ext_0.geometry}
          material={materials.material}
          rotation={[Math.PI, 1.348, -Math.PI]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Leaf_1005_Ext_0.geometry}
          material={materials.material}
          position={[-86.744, 32.106, -102.789]}
          rotation={[Math.PI, -0.945, Math.PI]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Leaf_1006_Ext_0.geometry}
          material={materials.material}
          position={[-97.903, 50.365, -83.804]}
          rotation={[Math.PI, -0.548, Math.PI]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Leaft_3001_Ext_0.geometry}
          material={materials.material}
          position={[326.677, -6.369, -260.77]}
          rotation={[0, -0.629, 0]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Leaf_1007_Ext_0.geometry}
          material={materials.material}
          position={[-241.496, 20.706, -337.442]}
          rotation={[0, 0.662, 0]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Leaf_1008_Ext_0.geometry}
          material={materials.material}
          position={[-253.006, 11.197, -326.273]}
          rotation={[0, 0.662, 0]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Leaf_1009_Ext_0.geometry}
          material={materials.material}
          position={[32.451, 24.804, 423.837]}
          rotation={[0, -0.072, 0]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Leaf_1_Ext_0.geometry}
          material={materials.material}
          position={[-8.51, 9.67, 424.488]}
          rotation={[Math.PI, 0.072, -Math.PI]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Leaft_3002_Ext_0.geometry}
          material={materials.material}
          position={[221.93, -6.762, 360.332]}
          rotation={[-3, -0.571, -3.065]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Leaft_3003_Ext_0.geometry}
          material={materials.material}
          position={[258.154, -3.468, 327.999]}
          rotation={[-3.006, -0.506, 3.091]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Blim_Blim003_Ext_0.geometry}
          material={materials.material}
          position={[3.799, 359.772, 0.444]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Blim_Blim002_Ext_0.geometry}
          material={materials.material}
          position={[83.1, 265.514, 0.444]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Blim_Blim001_Ext_0.geometry}
          material={materials.material}
          position={[-27.392, 232.316, 0.444]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Blim_Blim004_Ext_0.geometry}
          material={materials.material}
          position={[36.536, 440.765, 0.444]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Blim_Blim005_Ext_0.geometry}
          material={materials.material}
          position={[-3.091, 286.602, 0.444]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Blim_Blim_Ext_0.geometry}
          material={materials.material}
          position={[110.498, 419.004, 0.444]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Leaft_3_Ext_0.geometry}
          material={materials.material}
          position={[-347.038, -6.369, 218.343]}
          rotation={[-2.79, 0.961, 2.849]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Base_Base_0.geometry}
          material={materials.Base}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Base001_Ext_0.geometry}
          material={materials.material}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Background_Background_0.geometry}
          material={materials.Background}
          rotation={[0, -0.056, 0]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Leaf_1011_Ext_0.geometry}
          material={materials.material}
          position={[24.367, 174.327, 17.647]}
          rotation={[-3.086, -0.003, -2.922]}
          scale={100}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/magical_find.glb");
