/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Adan (https://sketchfab.com/Apdigivid.)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/lowpoly-lady-bug-90b59b5185b14c52944573f236eb7175
Title: Lowpoly Lady Bug
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function Model(props) {
  const { nodes, materials } = useGLTF("/lowpoly_lady_bug.glb");
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group
          position={[0.875, -1.599, 10.173]}
          rotation={[-0.258, 0, 0]}
          scale={0.247}
        >
          <group
            position={[0.015, -1.016, 4.042]}
            rotation={[1.179, 0.585, 1.026]}
          >
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Shell_Right005_0.geometry}
              material={materials["Lady_Red.001"]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Shell_Right005_1.geometry}
              material={materials["Lady_White.001"]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Shell_Right005_2.geometry}
              material={materials["Lady_Black.001"]}
            />
          </group>
          <group
            position={[0.015, -1.016, 4.042]}
            rotation={[1.179, -0.585, -1.026]}
          >
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Shell_Left005_0.geometry}
              material={materials["Lady_Red.001"]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Shell_Left005_1.geometry}
              material={materials["Lady_White.001"]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Shell_Left005_2.geometry}
              material={materials["Lady_Black.001"]}
            />
          </group>
          <group position={[0.076, -0.996, 2.328]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Left_Leg_01037_0.geometry}
              material={materials["Lady_Black.001"]}
            />
            <group
              position={[0.865, -0.599, -0.224]}
              rotation={[0.822, 0.495, 0.696]}
            >
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Left_Leg_02199_0.geometry}
                material={materials["Lady_Black.001"]}
              />
              <group position={[1.476, -0.807, -0.107]}>
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Left_Leg_03037_0.geometry}
                  material={materials["Lady_Black.001"]}
                />
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Left_Leg_04037_0.geometry}
                  material={materials["Lady_Black.001"]}
                  position={[0.014, 0.05, -1.78]}
                />
              </group>
            </group>
          </group>
          <group position={[-0.545, -0.173, 2.02]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Left_Leg_01036_0.geometry}
              material={materials["Lady_Black.001"]}
            />
            <group
              position={[-1.073, 0.498, -0.076]}
              rotation={[0.314, -0.82, -0.334]}
            >
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Left_Leg_02198_0.geometry}
                material={materials["Lady_Black.001"]}
              />
              <group position={[-1.684, 0.737, 0.256]}>
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Left_Leg_03036_0.geometry}
                  material={materials["Lady_Black.001"]}
                />
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Left_Leg_04036_0.geometry}
                  material={materials["Lady_Black.001"]}
                  position={[-0.387, 0.061, -1.922]}
                />
              </group>
            </group>
          </group>
          <group position={[-0.076, -0.996, 2.328]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Left_Leg_01035_0.geometry}
              material={materials["Lady_Black.001"]}
            />
            <group
              position={[-0.865, -0.599, -0.224]}
              rotation={[0.822, -0.402, -0.671]}
            >
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Left_Leg_02197_0.geometry}
                material={materials["Lady_Black.001"]}
              />
              <group position={[-1.476, -0.807, -0.107]}>
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Left_Leg_03035_0.geometry}
                  material={materials["Lady_Black.001"]}
                />
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Left_Leg_04035_0.geometry}
                  material={materials["Lady_Black.001"]}
                  position={[-0.014, 0.05, -1.78]}
                />
              </group>
            </group>
          </group>
          <group position={[0.545, -0.173, 2.02]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Left_Leg_01034_0.geometry}
              material={materials["Lady_Black.001"]}
            />
            <group
              position={[1.073, 0.498, -0.076]}
              rotation={[0.156, 0.947, 0.397]}
            >
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Left_Leg_02196_0.geometry}
                material={materials["Lady_Black.001"]}
              />
              <group position={[1.684, 0.737, 0.256]}>
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Left_Leg_03034_0.geometry}
                  material={materials["Lady_Black.001"]}
                />
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Left_Leg_04034_0.geometry}
                  material={materials["Lady_Black.001"]}
                  position={[0.387, 0.061, -1.922]}
                />
              </group>
            </group>
          </group>
          <group position={[0.516, 1.251, 1.867]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Left_Leg_01033_0.geometry}
              material={materials["Lady_Black.001"]}
            />
            <group
              position={[0.823, 0.805, -0.054]}
              rotation={[0.318, 0.948, -0.006]}
            >
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Left_Leg_02195_0.geometry}
                material={materials["Lady_Black.001"]}
              />
              <group position={[1.485, 1.028, 0.029]}>
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Left_Leg_03033_0.geometry}
                  material={materials["Lady_Black.001"]}
                />
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Left_Leg_04033_0.geometry}
                  material={materials["Lady_Black.001"]}
                  position={[-0.472, 0.918, -1.605]}
                />
              </group>
            </group>
          </group>
          <group position={[-0.516, 1.251, 1.867]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Left_Leg_01032_0.geometry}
              material={materials["Lady_Black.001"]}
            />
            <group
              position={[-0.823, 0.805, -0.054]}
              rotation={[0.557, -0.723, 0.323]}
            >
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Left_Leg_02194_0.geometry}
                material={materials["Lady_Black.001"]}
              />
              <group position={[-1.485, 1.028, 0.029]}>
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Left_Leg_03032_0.geometry}
                  material={materials["Lady_Black.001"]}
                />
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Left_Leg_04032_0.geometry}
                  material={materials["Lady_Black.001"]}
                  position={[0.472, 0.918, -1.605]}
                />
              </group>
            </group>
          </group>
          <group position={[0, -1.757, 2.869]} rotation={[0.315, 0, 0]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Head016_0.geometry}
              material={materials["Lady_Black.001"]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Head016_1.geometry}
              material={materials["Lady_Eyes.001"]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Head016_2.geometry}
              material={materials["Lady_White.001"]}
            />
          </group>
          <group position={[0, 1.047, 2.333]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Body025_0.geometry}
              material={materials["Lady_Black.001"]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Body025_1.geometry}
              material={materials["Lady_White.001"]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Wing_Right005_0.geometry}
              material={materials["Wing.001"]}
              position={[0.867, -0.898, 1.558]}
              rotation={[0, -0.239, 0]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Wing_Left005_0.geometry}
              material={materials["Wing.001"]}
              position={[-0.867, -0.898, 1.558]}
              rotation={[0, 0.271, 0]}
            />
          </group>
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/lowpoly_lady_bug.glb");

